### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by gwatts** [opentracing-contrib/go-grpc#3]
Thanks for writing this - could you add a License file for it?  It's pretty much impossible to use it in many cases without an explicit license in place.

**Comment by eclipseo** [comment]
@iredelmeier @austinlparker can you set a license for this package?

**Comment by dholbach** [comment]
CCing @fho @rnburn

**Comment by dholbach** [comment]
Shall we just create a PR? Apache 2 seems to be used in e.g. https://github.com/opentracing-contrib/go-stdlib/blob/master/LICENSE

**Comment by yurishkuro** [comment]
pinning original authors of https://github.com/grpc-ecosystem/grpc-opentracing/

@kcamenzind @rnburn @bhs @hzariv 

Are there any issues with using APLv2 license for this package? https://github.com/grpc-ecosystem/grpc-opentracing/ used some odd license.

**Comment by rnburn** [comment]
Fine with me
