### ISSUE TITLE
Create a TAG

### ISSUE THREAD

**Issue by FranciscoKurpiel** [opentracing-contrib/go-grpc#4]
This repository has only the `main` branch, and the it was no touched for a while. Wouldn't be possible to create a tag for the current commit, even if it is a `0.x`, so we can vendor it properly?

**Comment by eleduardo** [comment]
I am in the same boat, it would be nice to have tags specially with go modules now... even if this project is to be deprecated in lieu of opentelemetry it would be nice to have a tag for modules

**Comment by lucacome** [comment]
https://github.com/opentracing-contrib/go-grpc/releases/tag/v0.1.0 is now released
